#!/usr/bin/env python3


# pylint: disable=invalid-name


"""Utility script to inspect a class's methods and their return types."""


from argparse import ArgumentParser
from importlib import import_module
from inspect import (getfullargspec, getmembers,
                     isdatadescriptor, isfunction,
                     signature)


arg_parser = ArgumentParser()
arg_parser.add_argument('class_qualname')
args = arg_parser.parse_args()


print(args.class_qualname)

module_name, class_name = args.class_qualname.rsplit('.', 1)
module = import_module(name=module_name)
cls = getattr(module, class_name)

print('\nProperties:')
for pty_name, pty in getmembers(cls, isdatadescriptor):
    if not pty_name.startswith('_'):
        return_annotation = pty.fget.__annotations__.get('return')
        print(f'- {pty_name}: {return_annotation}'
              if return_annotation
              else f'- {pty_name}')

print('\nMethods:')
for method_name, method in getmembers(cls, isfunction):
    print(f'\n- {method_name}{signature(method)}:'
          f'\n    {getfullargspec(method)}')
